services:
  - type: web
    name: tg-douyin-api
    runtime: node
    region: singapore
    plan: free
    buildCommand: npm ci && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3002
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: BOT_TOKEN
        sync: false
      - key: FRONTEND_URL
        value: https://douyin-nine-omega.vercel.app
      - key: DATABASE_URL
        fromDatabase:
          name: tg-douyin-db
          property: connectionString

databases:
  - name: tg-douyin-db
    region: singapore
    plan: free
    databaseName: tg_douyin
    user: tg_douyin_user
